data:
  minimum_interactions: 10000
  minimum_users: 100
  minimum_items: 100

preprocessing:
  strategy: implicit_feedback
  allowed_event_types:
    - view
    - addtocart
    - transaction
  event_weights:
    view: 1.0
    addtocart: 3.0
    transaction: 5.0
